### ISSUE TITLE
Module 5 review

### ISSUE THREAD

**Issue by hugh-emerson** [lawrencemark/DevOps-Course-Starter#7]
I'm creating this as an "issue" on GitHub because you didn't create a pull request. Please always create pull requests, it's easier to review and more helpful for you to see comments against specific lines of code.

The way you have done this you are missing a lot of the benefits of Docker.

- You are only building an image based on the main branch but we definitely want to be able to containerise any version of the codebase.
- You aren't taking advantage of Docker's layer caching, so every build will be slow. 
- You are cloning the whole repo which could be more than the image needs.

You should instead:
- Put a Dockerfile at the root of your project.
- In that Dockerfile have all the necessary instructions to install prerequisites
- Write a `COPY` command in the Dockerfile to copy files from your computer into the image rather than git cloning anything. The PDF explicitly told you to do this

Other important changes:
- Why do you bother with the overcomplicated setup of `firstrun.sh`? Anything that requires one time setup should be done in the image. You can `poetry install` while building the image and forget about creating a firstrun.sh file.
- I assume your ENTRYPOINT starts a shell rather than starting up the app for the above hack and also the other points in the README, but I don't think they're valid reasons. Change the ENTRYPOINT to start up the app with flask run.
    - Step "2" shouldn't be necessary. There shouldn't be any code changes needed between running it locally and in a container. If there's an issue with imports it's possibly because you're missing the `__init__.py` file in the utils folder.
    - I don't know what you mean by "To let you the Developer decide". Decide between what options? Flask vs gunicorn? If they really want to they can always override the entrypoint with `--entrypoint`, but there shouldn't be any need to run the app in dev mode with gunicorn. If they want to check it works with gunicorn, they can run the prod image.

Please have a go at the above and let us know if you have any questions. Some other, less important points:
- You are using `apk add python3` which doesn't specify a minor version. Python releases are deliberately **not** backwards compatible, and even when things say they are, it's safer to control your versions more explicitly than this. You could actually save yourself a fair bit of effort by using a base image that already has Python installed.
- Your shell scripts have a lot of shared lines. The point of the multistage Dockerfile is that shared setup could be in the base stage and then differences between prod/dev could be in the prod/dev stages.
- Dockerfile should be spelt with a capital D. If you're on Windows, you'll need to run something like `git mv dockerfile Dockerfile` to get git to notice the change.
- You could still keep Docker stuff in a subdirectory if you think it keeps the repo tidier. But then you will need to run the `docker 
build` command from the top level and specify the path to the Dockerfile with `-f`
- Rather than generating a launch script inside a shell script, why not just have a launch script .sh file committed to the repo?

**Comment by hugh-emerson** [comment]
I don't mean to sound negative, there is a lot of good stuff still, and I liked the thorough documentation, but you seem to be fighting against Docker rather than using it as intended.

**Comment by lawrencemark** [comment]
Hi Hugh, no problems at all. I'll drop you a Slack message at some stage next week. You're completely right by the way in what you say about the exercise: it's me being over sensitive to your comments and pressure at work Friday was through the roof and you got caught in the crossfire - that's my bad, so please excuse me. I'm one of those people who love the more assertive writing style/friendly type of updates and emails - anything other brings out Mr Angry. I won't lie, I love going freestyle when learning, also not forgetting I don't have other times to do it, and I'm hoping the new Module5.1 is what you're looking for. It seems far too simple to me though :)  I did make a blunder, in my rush to ensure everything is right, when updating my local git repo, I thought I'd create a new branch before updating and god knows how pushed to the remote main. I later created a branch for Module 5.1 with updates to the README and the new Dockerfile taking your points into account. Cheers, Mark
